import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/lib/utils";

import Navbar from "@/components/navbar";
import LinksBar from "@/components/links-bar";

const bodyfont = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-body antialiased", bodyfont.variable)}>
        <Navbar />
        <LinksBar />
        {children}
      </body>
    </html>
  );
}
